/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenssagemVotacao.java
 *
 * Created on 22/05/2011, 14:14:01
 */
package pitaqueiro;

import javax.swing.WindowConstants;

/**
 *
 * @author Lucas
 */
public class MenssagemVotacao extends javax.swing.JFrame {

    /** Creates new form MenssagemVotacao */
    public MenssagemVotacao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotaoSimVotar = new javax.swing.JButton();
        BotaoNaoVotar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Deseja dar sua opnião a respeito dos restaurantes?");

        BotaoSimVotar.setText("Sim");

        BotaoNaoVotar.setText("Não");
        BotaoNaoVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNaoVotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoSimVotar)
                        .addGap(27, 27, 27)
                        .addComponent(BotaoNaoVotar)
                        .addGap(124, 124, 124))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotaoNaoVotar, BotaoSimVotar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSimVotar)
                    .addComponent(BotaoNaoVotar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BotaoNaoVotar, BotaoSimVotar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoNaoVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNaoVotarActionPerformed
        //MenssagemVotacao.setDefaultClosedOpartion(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_BotaoNaoVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenssagemVotacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoNaoVotar;
    private javax.swing.JButton BotaoSimVotar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
